export const apikey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3cXZtbGtiY3NsbXlzdnRvc3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA3NTE3MDEsImV4cCI6MjAyNjMyNzcwMX0.qh0N_Fw_P8RVA_WhAcHzshFQ9zgHuhbOA3lztesPbuQ";
export const endpoint =
  "https://kwqvmlkbcslmysvtosts.supabase.co/rest/v1/name";
